- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew
  tags:
    - homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: "/opt/homebrew/bin"
  become: true
  tags:
    - homebrew
